version: '3.8'

services:

  axonserver:
    container_name: axon
    image: 649eb1d3fec8
    hostname: axon-server
    environment:
      - SERVER_PORT=8024
      - AXONIQ_AXONSERVER_PORT=8124
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - discover-gateway

  phone-database:
    container_name: phonedb
    image: e1d7dc9731da
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - discover-gateway
    ports:
    - '3306:3306'
    volumes:
    - C:\Users\HuyVo\mycode\my.cnf:/etc/mysql/my.cnf
    - C:\Users\HuyVo\mycode\db:/var/lib/mysql
    restart: always

  discover-server:
    container_name: discover-server
    build:
      context: ./discover-server
      dockerfile: Dockerfile
    networks:
      - discover-gateway
    ports:
      - '8761:8761'

  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - discover-server
      - phone-database
    ports:
      - '8084:8084'
    networks:
      - discover-gateway
    environment:
      - MYSQL_HOST=phone-database
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD=123456
    restart: on-failure

  product-service:
    container_name: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    networks:
      - discover-gateway
    depends_on:
      - discover-server
      - gateway
      - phone-database
      - axonserver
    links:
      - axonserver
    ports:
      - '8080:8080'
    environment:
      - MYSQL_HOST=phone-database
      - MYSQL_DATABASE=phone
      - MYSQL_ROOT_PASSWORD=123456
    restart: on-failure

  order-service:
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    networks:
      - discover-gateway
    depends_on:
      - discover-server
      - gateway
      - phone-database
      - axonserver
    links:
      - axonserver
    ports:
      - '8081:8081'
    environment:
      - MYSQL_HOST=phone-database
      - MYSQL_DATABASE=orders
      - MYSQL_ROOT_PASSWORD=123456
    restart: on-failure

networks:
  discover-gateway:
    driver: bridge
