export const GET_LIST_ORDER = 'GET_LIST_ORDER';
export const GET_LIST_ORDER_SUCCESS = 'GET_LIST_ORDER_SUCCESS';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const DELETE_ORDER = 'DELETE_ORDER';