export const GET_ALL_CODE = 'GET_ALL_CODE';
export const GET_ALL_CODE_SUCCESS = 'GET_ALL_CODE_SUCCESS';
export const SUBMIT_COUPON = 'SUBMIT_COUPON';
export const SUBMIT_COUPON_SUCCESS = 'SUBMIT_COUPON_SUCCESS';
export const SUBMIT_COUPON_FAILED = 'SUBMIT_COUPON_FAILED';