export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ALL_DETAILS = 'GET_ALL_DETAILS';
export const GET_ALL_DETAILS_SUCCESS = 'GET_ALL_DETAILS_SUCCESS'