export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCcESS = 'CREATE_ORDER_SUCcESS';
export const GET_ORDERID = 'GET_ORDERID';
export const GET_ORDERID_SUCCESS = 'GET_ORDERID_SUCCESS';