export const GET_PROMOTION_ACTIVE = 'GET_PROMOTION_ACTIVE';
export const GET_PROMOTION_ACTIVE_SUCCESS = 'GET_PROMOTION_ACTIVE_SUCCESS';
export const GET_ALL_PRODUCT_IN_PROMOTION_SUCCESS = 'GET_ALL_PRODUCT_IN_PROMOTION_SUCCESS';