export const GET_PRODUCTS_BY_TYPE = 'GET_PRODUCTS_BY_TYPE';
export const GET_PRODUCT_BY_TYPE_SUCCESS = 'GET_PRODUCT_BY_TYPE_SUCCESS';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS';
